console:
  port: 7351
  username: "admin"
  password: "Ondi@2025"
  max_message_size_bytes: 409600
logger:
  level: "INFO"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
database:
  address:
    - "postgres://root:Ondi2025@128.199.91.28:26257/test"